export {
  outlineStrokes,
  simplifyStroke,
  strokesBounds,
  translateStrokes,
  type Bounds,
  type GlyphStrokes,
  type OutlineSink,
  type Point,
  type Stroke,
} from "@/lib/scrawl/geometry";
export {
  ACCENT_COMPOSITES,
  ACCENT_MARKS,
  BASE_CHARSET,
  BOX_BOTTOM,
  BOX_HEIGHT,
  BOX_TOP,
  BOX_WIDTH,
  BRUSH_RANGE,
  CAP_HEIGHT,
  CHARACTER_GROUPS,
  CHARSET,
  CHARSET_WITH_ACCENTS_COUNT,
  DEFAULT_SETTINGS,
  FONT_ASCENDER,
  FONT_DESCENDER,
  GLYPH_NAMES,
  GUIDE_LINES,
  MARKS,
  PANGRAM,
  PEN_RADIUS,
  SIDE_BEARING,
  SIDE_BEARING_RANGE,
  SPACE_ADVANCE,
  UNITS_PER_EM,
  WORD_SPACE_RANGE,
  X_HEIGHT,
  resolveSettings,
  type AccentComposite,
  type FontSettings,
  type FontWeightName,
} from "@/lib/scrawl/metrics";
export {
  buildFontBuffer,
  countDrawn,
  expandGlyphs,
  fileSafeName,
  isDrawn,
  otfToWoff,
  type GlyphMap,
} from "@/lib/scrawl/font-build";
export { buildFontPackage, downloadFontPackage, type PackageFile } from "@/lib/scrawl/export";
export { createZip, downloadBlob, type ZipEntry } from "@/lib/scrawl/zip";
